In [1]:
import numpy as np

In [2]:
arr_1=np.array([1,3,5,7,9])
arr_1

array([1, 3, 5, 7, 9])

In [3]:
type(arr_1)

numpy.ndarray

In [4]:
arr_1.shape

(5,)

In [5]:
arr_1.size

5

In [6]:
arr_1.ndim

1

In [7]:
arr_2=np.array([[2,4,6,8],[3,5,7,9],[1,4,7,10]])
arr_2

array([[ 2,  4,  6,  8],
       [ 3,  5,  7,  9],
       [ 1,  4,  7, 10]])

In [8]:
arr_2.ndim

2

In [9]:
arr_2.shape

(3, 4)

In [10]:
arr_2.size

12

In [11]:
type(arr_2)

numpy.ndarray

In [12]:
arr_2.dtype

dtype('int32')

In [13]:
mx_1= np.ones((4,5), dtype = int)
mx_1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
mx_1.shape

(4, 5)

In [15]:
mx_0= np.zeros((4,5), dtype = int)
mx_0

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [16]:
mx_1= np.ones((4,5), dtype = bool)
mx_1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [17]:
mx_0= np.zeros((4,5), dtype =  bool)
mx_0

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [18]:
mx_0= np.zeros((4,5), dtype =  str)
mx_0

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [19]:
mx_empty= np.empty((4,6))
mx_empty

array([[6.23042070e-307, 3.56043053e-307, 1.37961641e-306,
        8.90071135e-308, 8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 1.33510679e-306,
        2.22522597e-306, 1.60220393e-306, 6.89805151e-307],
       [7.56592338e-307, 6.89807188e-307, 7.56589622e-307,
        1.33510882e-306, 1.37961370e-306, 1.69118515e-306],
       [7.56598449e-307, 8.45559303e-307, 1.06811422e-306,
        1.05694828e-307, 1.42410974e-306, 2.22507386e-306]])

In [20]:
mx_empty.dtype

dtype('float64')

In [21]:
ar_1 = np.arange(1,24,2)
print(ar_1)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [22]:
ar_2=ar_1.reshape(3,4)
ar_2

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [23]:
ar_3= ar_1.reshape(2,2,3)
ar_3

array([[[ 1,  3,  5],
        [ 7,  9, 11]],

       [[13, 15, 17],
        [19, 21, 23]]])

In [24]:
ar_3.ravel()


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [25]:
ar_3.flatten()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [26]:
ar_3.transpose()

array([[[ 1, 13],
        [ 7, 19]],

       [[ 3, 15],
        [ 9, 21]],

       [[ 5, 17],
        [11, 23]]])

In [27]:
aman=np.arange(2,14).reshape(4,3)
aman

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [28]:
anant=np.arange(1,13).reshape(4,3)
anant

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
aman+anant

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [30]:
add= np.add(aman,anant)
add

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [31]:
aman-anant

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [32]:
sub= np.subtract(aman,anant)
sub

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [33]:
aman*anant

array([[  2,   6,  12],
       [ 20,  30,  42],
       [ 56,  72,  90],
       [110, 132, 156]])

In [34]:
np.multiply(aman,anant)

array([[  2,   6,  12],
       [ 20,  30,  42],
       [ 56,  72,  90],
       [110, 132, 156]])

In [35]:
aman/anant

array([[2.        , 1.5       , 1.33333333],
       [1.25      , 1.2       , 1.16666667],
       [1.14285714, 1.125     , 1.11111111],
       [1.1       , 1.09090909, 1.08333333]])

In [36]:
np.divide(aman,anant)

array([[2.        , 1.5       , 1.33333333],
       [1.25      , 1.2       , 1.16666667],
       [1.14285714, 1.125     , 1.11111111],
       [1.1       , 1.09090909, 1.08333333]])

In [37]:
aman @ anant

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [ ]:
amna.dot(anant)

NameError: name 'amna' is not defined

In [ ]:
np.max(aman)

13

In [ ]:
np.max(anant)

12

In [ ]:
np.min(aman)

2

In [ ]:
np.min(anant)

1

In [ ]:
np.argmax(aman)

11

In [ ]:
np.argmin(anant)

0

In [ ]:
aman.max(axis=1)

array([ 4,  7, 10, 13])

In [ ]:
aman.max(axis=0)

array([11, 12, 13])

In [ ]:
anant.min(axis=0)

array([1, 2, 3])

In [ ]:
anant.min(axis=1)

array([ 1,  4,  7, 10])

In [ ]:
np.sum(anant)

78

In [ ]:
np.mean(anant)

6.5

In [ ]:
np.std(anant)

3.452052529534663

In [ ]:
np.exp(anant)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [ ]:
np.log(anant)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665]])

In [ ]:
np.log10(anant)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251],
       [1.        , 1.04139269, 1.07918125]])